In [ ]:
#idomatic
#transformation code into beatiful,idomatic python


In [1]:
#looping over a range of numbers
for i in [0,1,2,3,4]:
    print(i**2,end=' ')
print()

#pythonic way
for  i in range(5):
    print(i**2,end=' ')
    

0 1 4 9 16 
0 1 4 9 16 

In [2]:
#looping over collection(list)
li=[1,2,3,4,5]
for i in range(len(li)):
    print(li[i],end=' ')
print()

#pythonic way
for i in li:
    print(i,end=' ')

1 2 3 4 5 
1 2 3 4 5 

In [3]:
#looping from backword in traditional way
li=[1,2,3,4,5,6]
for i in range(len(li)-1,-1,-1):
    print(li[i],end=' ')
print()    
#pythonic way
for i in reversed(li):
    print(i,end=' ')
    

6 5 4 3 2 1 
6 5 4 3 2 1 

In [4]:
li=[1,2,3,4,5]
for i in range(len(li)):
    print(i,'-->',li[i])
print()
#pythonic way or idomatic
for i,a in enumerate(li):
    print(i,'-->',a)

0 --> 1
1 --> 2
2 --> 3
3 --> 4
4 --> 5

0 --> 1
1 --> 2
2 --> 3
3 --> 4
4 --> 5


In [5]:
#looping over two collections
li=[1,2,4,5,6]
a=[1,3,4,5,6,8,7]
n=min(len(li),len(a))
for i in range(n):
    print(li[i],' ',a[i])
print()


#pthonic approach
for i,a in zip(li,a):
    print(i,' ',a)
    

1   1
2   3
4   4
5   5
6   6

1   1
2   3
4   4
5   5
6   6


In [6]:
li=[1,2,4,5,6,6,7888,888]
a=[1,3,4,5,6,8,7]
n=min(len(li),len(a))

li.sort()

In [7]:
li=[4,7,3,9,12,54,65]
for i in sorted(li):
    print(i,end=' ')
print()

for i in sorted(li,reverse=True):
    print(i,end=' ')

3 4 7 9 12 54 65 
65 54 12 9 7 4 3 

In [14]:
d={'name':'anil','email':'anil@gmail','address':'githam'}
for i in d:
    print(i,end=' ')
print()

for i in d.keys():
    if i.startswith('a'):
        del[d[i]]

NameError: name 'name' is not defined

In [16]:
#list comprehenshion

In [20]:
#traditional way
li=[]
for i in range(5):
    k=i**2
    li.append(k)
print(sum(li[i]))
print()

#pythonic way
print(sum(i**2 for i in range(5)))

    

TypeError: 'int' object is not iterable

In [ ]:

for i in range(5):
  
 print(i)

In [18]:
x=[i%2==0 for i in range(6)]
print(x)

[True, False, True, False, True, False]


# lambda
anonmous function

In [22]:
#lambda with map()

In [23]:
def squarelist(li):
    a=[]
    for i in li:
        a.append(i*2)
    return a
li=[1,2,3,4,6,7]
squarelist(li)

[2, 4, 6, 8, 12, 14]

In [24]:
li=[1,2,3,4,6,7]
y=list(map(lambda x:x*2,li))
print(y)

[2, 4, 6, 8, 12, 14]


In [26]:
li=[1,2,3,4,6,7]
z=list(reduce(lambda x,y:x+y,li))
print(z)

NameError: name 'reduce' is not defined

# standard package
pandas,Numpy and Matplotlib


#pandas for data cleaning,data transformation,data analysis
##notations
  -series ---it is a single dimentional
  
   -data frame   multi-dimentional

In [10]:
import pandas as pd
internal={'s1':35,'s2':46,'s3':76,'s4':89}
internal2={'s1':30,'s2':45,'s3':77,'s4':80}
x=pd.Series(internal)
y=pd.Series(internal2)
print(x)
print(y)

s1    35
s2    46
s3    76
s4    89
dtype: int64
s1    30
s2    45
s3    77
s4    80
dtype: int64


In [11]:
final={'internal':x,'internal2':y}
final=pd.DataFrame(final)
print(final)

    internal  internal2
s1        35         30
s2        46         45
s3        76         77
s4        89         80


In [12]:
final.keys

<bound method NDFrame.keys of     internal  internal2
s1        35         30
s2        46         45
s3        76         77
s4        89         80>

In [13]:
final.values

array([[35, 30],
       [46, 45],
       [76, 77],
       [89, 80]], dtype=int64)

In [50]:
final.values[2] #index for rows 2

array([90, 77], dtype=int64)

In [51]:
final.values[2][0]

90

In [52]:
final.values[2][0]=90 #takes 2 row 0th element
print(final)

    internal  internal2
s1        35         30
s2        46         45
s3        90         77
s4        89         80
5         57         89


In [53]:
final.loc[5]=[57,89]
final.values

array([[35, 30],
       [46, 45],
       [90, 77],
       [89, 80],
       [57, 89]], dtype=int64)

In [54]:
pwd

'C:\\Users\\Ramesh'

In [30]:
import pandas as pd
filepath = r"C:\Users\Ramesh\gitam-pandas\Income.csv"
def pddata(filepath):
    return pd.read_csv(filepath)
df=pddata(filepath)
print(df)

       GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  62993  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528  


In [56]:
for row in df.values:
    print(row[1], ' : ',row[-1])
    
    

Alabama  :  41381
Alaska  :  61137
Arizona  :  50602
Arkansas  :  39919
California  :  57528


In [57]:
df.values

array([['04000US01', 'Alabama', 37150, 37952, 42212, 44476, 39980, 40933,
        42590, 43464, 41381],
       ['04000US02', 'Alaska', 55891, 56418, 62993, 63989, 61604, 57848,
        57431, 63648, 61137],
       ['04000US04', 'Arizona', 45245, 46657, 62993, 46914, 45739, 46896,
        48621, 47044, 50602],
       ['04000US05', 'Arkansas', 36658, 37057, 40795, 39586, 36538,
        38587, 41302, 39018, 39919],
       ['04000US06', 'California', 51755, 55319, 55734, 57014, 56134,
        54283, 53367, 57020, 57528]], dtype=object)

In [58]:
def average():
    s=0
    for i in range(2,11):
        s+=df.values[4][i]
    return s//len(df.values[4][2:])
average()

55350

In [79]:
#whic only displays coloum name in the list
cl=df.columns.values()
c1=list(cl)

TypeError: 'numpy.ndarray' object is not callable

In [75]:
li=[]
def clis(li):
    for i in c1:
        li.append(i)
    return li
type(clis(li))

NameError: name 'c1' is not defined

In [31]:
pwd

'C:\\Users\\Ramesh'

In [31]:

fpath='gitam-pandas\RegularSeasonCompactResults.csv'
def pddata(fpath):
    return pd.read_csv(fpath)
df=pddata(fpath)
df.head()

Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
0    1985      20   1228      81   1328      64    N      0
1    1985      25   1106      77   1354      70    H      0
2    1985      25   1112      63   1223      56    H      0
3    1985      25   1165      70   1432      54    H      0
4    1985      25   1192      86   1447      74    H      0

In [33]:
df.shape

(145289, 8)

In [34]:
df.head()

Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
0    1985      20   1228      81   1328      64    N      0
1    1985      25   1106      77   1354      70    H      0
2    1985      25   1112      63   1223      56    H      0
3    1985      25   1165      70   1432      54    H      0
4    1985      25   1192      86   1447      74    H      0

In [35]:
df.tail()

Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
145284    2016     132   1114      70   1419      50    N      0
145285    2016     132   1163      72   1272      58    N      0
145286    2016     132   1246      82   1401      77    N      1
145287    2016     132   1277      66   1345      62    N      0
145288    2016     132   1386      87   1433      74    N      0

In [36]:
df.describe()

Season         Daynum          Wteam         Wscore  \
count  145289.000000  145289.000000  145289.000000  145289.000000   
mean     2001.574834      75.223816    1286.720646      76.600321   
std         9.233342      33.287418     104.570275      12.173033   
min      1985.000000       0.000000    1101.000000      34.000000   
25%      1994.000000      47.000000    1198.000000      68.000000   
50%      2002.000000      78.000000    1284.000000      76.000000   
75%      2010.000000     103.000000    1379.000000      84.000000   
max      2016.000000     132.000000    1464.000000     186.000000   

               Lteam         Lscore          Numot  
count  145289.000000  145289.000000  145289.000000  
mean     1282.864064      64.497009       0.044387  
std       104.829234      11.380625       0.247819  
min      1101.000000      20.000000       0.000000  
25%      1191.000000      57.000000       0.000000  
50%      1280.000000      64.000000       0.000000  
75%      1375.000000      72.000000       0.000000  
max      1464.000000     150.000000       6.000000

In [37]:
df.columns.tolist()

['Season', 'Daynum', 'Wteam', 'Wscore', 'Lteam', 'Lscore', 'Wloc', 'Numot']

In [38]:

df.max()

Season    2016
Daynum     132
Wteam     1464
Wscore     186
Lteam     1464
Lscore     150
Wloc         N
Numot        6
dtype: object

In [39]:



df['Lteam'].max()

1464

In [40]:
df['Lteam'].min()

1101

In [41]:
df.sort_values('Lscore').head()

Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
100027    2008      66   1203      49   1387      20    H      0
49310     1997      66   1157      61   1204      21    H      0
89021     2006      44   1284      41   1343      21    A      0
85042     2005      66   1131      73   1216      22    H      0
103660    2009      26   1326      59   1359      22    H      0

In [42]:
#filter the row based on condition
df[df['Wscore']>170]

Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
17867    1989      92   1258     181   1109     150    H      0
19653    1990      30   1328     173   1109     101    H      0
24341    1991      47   1328     172   1258     112    H      0
24970    1991      68   1258     186   1109     140    H      0

In [43]:

df.keys()

Index(['Season', 'Daynum', 'Wteam', 'Wscore', 'Lteam', 'Lscore', 'Wloc',
       'Numot'],
      dtype='object')

In [44]:
print(df['Lteam'])

0         1328
1         1354
2         1223
3         1432
4         1447
5         1337
6         1226
7         1268
8         1133
9         1424
10        1288
11        1438
12        1411
13        1397
14        1225
15        1368
16        1391
17        1306
18        1388
19        1184
20        1159
21        1216
22        1134
23        1296
24        1265
25        1416
26        1137
27        1149
28        1102
29        1114
          ... 
145259    1328
145260    1418
145261    1103
145262    1396
145263    1308
145264    1361
145265    1354
145266    1253
145267    1452
145268    1208
145269    1408
145270    1268
145271    1330
145272    1438
145273    1428
145274    1276
145275    1437
145276    1394
145277    1238
145278    1173
145279    1436
145280    1261
145281    1426
145282    1172
145283    1285
145284    1419
145285    1272
145286    1401
145287    1345
145288    1433
Name: Lteam, Length: 145289, dtype: int64
